// GENERATED by scripts/export-sprites.mjs from the designs in art/designs.
// Do not edit by hand: change a design (or the script) and run `npm run export:sprites`.

/** Where Thor stands on the longship, in the boat design's units. */
export const BOAT_ANCHOR = [1300,1720];

/**
 * One entry per animation. `scale` is design units to sheet pixels;
 * originX/originY (0..1) mark the anchor inside a frame (Thor's feet, a
 * draugr's waterline, Thor's spot on the deck); `parts` lists the sheet
 * files, in frame order.
 */
export const SPRITES = {
  boat: {
    scale: 0.32,
    frameWidth: 1280,
    frameHeight: 617,
    frames: 1,
    spacing: 2,
    originX: 0.5,
    originY: 0.824,
    parts: [
      {
        key: 'boat',
        url: 'assets/sprites/boat.webp',
        frames: 1
      }
    ]
  },
  'thor-idle': {
    scale: 0.32,
    frameWidth: 166,
    frameHeight: 338,
    frames: 8,
    spacing: 2,
    originX: 0.4277,
    originY: 0.9716,
    parts: [
      {
        key: 'thor-idle',
        url: 'assets/sprites/thor-idle.webp',
        frames: 8
      }
    ]
  },
  'thor-raise': {
    scale: 0.32,
    frameWidth: 300,
    frameHeight: 471,
    frames: 10,
    spacing: 2,
    originX: 0.3333,
    originY: 0.9881,
    parts: [
      {
        key: 'thor-raise',
        url: 'assets/sprites/thor-raise.webp',
        frames: 10
      }
    ]
  },
  'thor-atk2': {
    scale: 0.32,
    frameWidth: 304,
    frameHeight: 477,
    frames: 8,
    spacing: 2,
    originX: 0.3487,
    originY: 0.9862,
    parts: [
      {
        key: 'thor-atk2',
        url: 'assets/sprites/thor-atk2.webp',
        frames: 8
      }
    ]
  },
  'thor-atk3': {
    scale: 0.32,
    frameWidth: 396,
    frameHeight: 517,
    frames: 10,
    spacing: 2,
    originX: 0.4217,
    originY: 0.9099,
    parts: [
      {
        key: 'thor-atk3',
        url: 'assets/sprites/thor-atk3.webp',
        frames: 10
      }
    ]
  },
  'thor-hurt': {
    scale: 0.32,
    frameWidth: 357,
    frameHeight: 351,
    frames: 12,
    spacing: 2,
    originX: 0.479,
    originY: 0.9726,
    parts: [
      {
        key: 'thor-hurt',
        url: 'assets/sprites/thor-hurt.webp',
        frames: 12
      }
    ]
  },
  'thor-death': {
    scale: 0.32,
    frameWidth: 401,
    frameHeight: 354,
    frames: 10,
    spacing: 2,
    originX: 0.5162,
    originY: 0.9729,
    parts: [
      {
        key: 'thor-death',
        url: 'assets/sprites/thor-death.webp',
        frames: 10
      }
    ]
  },
  'draugr-walk': {
    scale: 0.32,
    frameWidth: 328,
    frameHeight: 344,
    frames: 12,
    spacing: 2,
    originX: 0.497,
    originY: 0.626,
    parts: [
      {
        key: 'draugr-walk',
        url: 'assets/sprites/draugr-walk.webp',
        frames: 12
      }
    ]
  },
  'draugr-death': {
    scale: 0.32,
    frameWidth: 366,
    frameHeight: 479,
    frames: 12,
    spacing: 2,
    originX: 0.5,
    originY: 0.7314,
    parts: [
      {
        key: 'draugr-death',
        url: 'assets/sprites/draugr-death.webp',
        frames: 12
      }
    ]
  },
  sea: {
    scale: 0.32,
    frameWidth: 640,
    frameHeight: 384,
    frames: 16,
    spacing: 2,
    originX: 0,
    originY: 0,
    parts: [
      {
        key: 'sea-0',
        url: 'assets/sprites/sea-0.webp',
        frames: 15
      },
      {
        key: 'sea-1',
        url: 'assets/sprites/sea-1.webp',
        frames: 1
      }
    ]
  }
};
