// GENERATED by scripts/export-sprites.mjs from the designs in art/designs.
// Do not edit by hand: change a design (or the script) and run `npm run export:sprites`.

/** Design units to game pixels used for every sprite. */
export const SPRITE_SCALE = 0.32;

/** Where Thor stands on the longship, in the boat design's units. */
export const BOAT_ANCHOR = [1300,1720];

/**
 * One entry per sprite sheet. originX/originY (0..1) mark the anchor inside a
 * frame: Thor's feet, or the spot on the deck where Thor stands.
 */
export const SPRITES = {
  boat: {
    url: 'assets/sprites/boat.webp',
    frameWidth: 1280,
    frameHeight: 617,
    frames: 1,
    spacing: 2,
    originX: 0.5,
    originY: 0.824
  },
  'thor-idle': {
    url: 'assets/sprites/thor-idle.webp',
    frameWidth: 166,
    frameHeight: 338,
    frames: 8,
    spacing: 2,
    originX: 0.4277,
    originY: 0.9716
  },
  'thor-raise': {
    url: 'assets/sprites/thor-raise.webp',
    frameWidth: 300,
    frameHeight: 471,
    frames: 10,
    spacing: 2,
    originX: 0.3333,
    originY: 0.9881
  },
  'thor-atk2': {
    url: 'assets/sprites/thor-atk2.webp',
    frameWidth: 304,
    frameHeight: 477,
    frames: 8,
    spacing: 2,
    originX: 0.3487,
    originY: 0.9862
  },
  'thor-atk3': {
    url: 'assets/sprites/thor-atk3.webp',
    frameWidth: 396,
    frameHeight: 517,
    frames: 10,
    spacing: 2,
    originX: 0.4217,
    originY: 0.9099
  },
  'thor-hurt': {
    url: 'assets/sprites/thor-hurt.webp',
    frameWidth: 357,
    frameHeight: 351,
    frames: 12,
    spacing: 2,
    originX: 0.479,
    originY: 0.9726
  },
  'thor-death': {
    url: 'assets/sprites/thor-death.webp',
    frameWidth: 401,
    frameHeight: 354,
    frames: 10,
    spacing: 2,
    originX: 0.5162,
    originY: 0.9729
  }
};
